chunkBuildingBatchSize=12
chunkBuildingThreads=6
chunkBuildingTotalBatches=12
collectChunkEmission=true
denoiserMode=1
dlssMode=1
inactivityFpsLimit=30
maxFps=260
rayBounces=4
upscalerQuality=1
upscalerType=1
vsync=true
